"""국가 목록 (ISO 3166-1 alpha-3, 한국어명, 영문명).

Plotly 세계지도(UN 50m)에 포함된 국가·지역만 담았다.
"""

# (iso3, 한국어명, 영문명)
COUNTRIES = [
    ('GHA', '가나', 'Ghana'),
    ('GAB', '가봉', 'Gabon'),
    ('GUY', '가이아나', 'Guyana'),
    ('GMB', '감비아', 'Gambia'),
    ('GGY', '건지', 'Guernsey'),
    ('GLP', '과들루프', 'Guadeloupe'),
    ('GTM', '과테말라', 'Guatemala'),
    ('GUM', '괌', 'Guam'),
    ('GRD', '그레나다', 'Grenada'),
    ('GRC', '그리스', 'Greece'),
    ('GRL', '그린란드', 'Greenland'),
    ('GIN', '기니', 'Guinea'),
    ('GNB', '기니비사우', 'Guinea-Bissau'),
    ('NAM', '나미비아', 'Namibia'),
    ('NRU', '나우루', 'Nauru'),
    ('NGA', '나이지리아', 'Nigeria'),
    ('SSD', '남수단', 'South Sudan'),
    ('ZAF', '남아프리카', 'South Africa'),
    ('NLD', '네덜란드', 'Netherlands'),
    ('BES', '네덜란드령 카리브', 'Bonaire, Sint Eustatius and Saba'),
    ('NPL', '네팔', 'Nepal'),
    ('NOR', '노르웨이', 'Norway'),
    ('NFK', '노퍽섬', 'Norfolk Island'),
    ('NZL', '뉴질랜드', 'New Zealand'),
    ('NCL', '뉴칼레도니아', 'New Caledonia'),
    ('NIU', '니우에', 'Niue'),
    ('NER', '니제르', 'Niger'),
    ('NIC', '니카라과', 'Nicaragua'),
    ('TWN', '대만', 'Taiwan'),
    ('KOR', '대한민국', 'South Korea'),
    ('DNK', '덴마크', 'Denmark'),
    ('DMA', '도미니카', 'Dominica'),
    ('DOM', '도미니카 공화국', 'Dominican Republic'),
    ('DEU', '독일', 'Germany'),
    ('TLS', '동티모르', 'Timor-Leste'),
    ('LAO', '라오스', 'Laos'),
    ('LBR', '라이베리아', 'Liberia'),
    ('LVA', '라트비아', 'Latvia'),
    ('RUS', '러시아', 'Russian Federation'),
    ('LBN', '레바논', 'Lebanon'),
    ('LSO', '레소토', 'Lesotho'),
    ('REU', '레위니옹', 'Réunion'),
    ('ROU', '루마니아', 'Romania'),
    ('LUX', '룩셈부르크', 'Luxembourg'),
    ('RWA', '르완다', 'Rwanda'),
    ('LBY', '리비아', 'Libya'),
    ('LTU', '리투아니아', 'Lithuania'),
    ('LIE', '리히텐슈타인', 'Liechtenstein'),
    ('MDG', '마다가스카르', 'Madagascar'),
    ('MTQ', '마르티니크', 'Martinique'),
    ('MHL', '마셜 제도', 'Marshall Islands'),
    ('MYT', '마요트', 'Mayotte'),
    ('MAC', '마카오', 'Macao'),
    ('MWI', '말라위', 'Malawi'),
    ('MYS', '말레이시아', 'Malaysia'),
    ('MLI', '말리', 'Mali'),
    ('IMN', '맨섬', 'Isle of Man'),
    ('MEX', '멕시코', 'Mexico'),
    ('MCO', '모나코', 'Monaco'),
    ('MAR', '모로코', 'Morocco'),
    ('MUS', '모리셔스', 'Mauritius'),
    ('MRT', '모리타니', 'Mauritania'),
    ('MOZ', '모잠비크', 'Mozambique'),
    ('MNE', '몬테네그로', 'Montenegro'),
    ('MSR', '몬트세라트', 'Montserrat'),
    ('MDA', '몰도바', 'Moldova'),
    ('MDV', '몰디브', 'Maldives'),
    ('MLT', '몰타', 'Malta'),
    ('MNG', '몽골', 'Mongolia'),
    ('USA', '미국', 'United States'),
    ('VIR', '미국령 버진아일랜드', 'Virgin Islands, U.S.'),
    ('MMR', '미얀마', 'Myanmar'),
    ('FSM', '미크로네시아', 'Micronesia, Federated States of'),
    ('VUT', '바누아투', 'Vanuatu'),
    ('BHR', '바레인', 'Bahrain'),
    ('BRB', '바베이도스', 'Barbados'),
    ('BHS', '바하마', 'Bahamas'),
    ('BGD', '방글라데시', 'Bangladesh'),
    ('BMU', '버뮤다', 'Bermuda'),
    ('BEN', '베냉', 'Benin'),
    ('VEN', '베네수엘라', 'Venezuela'),
    ('VNM', '베트남', 'Vietnam'),
    ('BEL', '벨기에', 'Belgium'),
    ('BLR', '벨라루스', 'Belarus'),
    ('BLZ', '벨리즈', 'Belize'),
    ('BIH', '보스니아 헤르체고비나', 'Bosnia and Herzegovina'),
    ('BWA', '보츠와나', 'Botswana'),
    ('BOL', '볼리비아', 'Bolivia'),
    ('BDI', '부룬디', 'Burundi'),
    ('BFA', '부르키나파소', 'Burkina Faso'),
    ('BTN', '부탄', 'Bhutan'),
    ('MNP', '북마리아나제도', 'Northern Mariana Islands'),
    ('MKD', '북마케도니아', 'North Macedonia'),
    ('PRK', '북한', 'North Korea'),
    ('BGR', '불가리아', 'Bulgaria'),
    ('BRA', '브라질', 'Brazil'),
    ('BRN', '브루나이', 'Brunei Darussalam'),
    ('WSM', '사모아', 'Samoa'),
    ('SAU', '사우디아라비아', 'Saudi Arabia'),
    ('STP', '상투메 프린시페', 'Sao Tome and Principe'),
    ('MAF', '생마르탱', 'Saint Martin (French part)'),
    ('BLM', '생바르텔레미', 'Saint Barthélemy'),
    ('SPM', '생피에르 미클롱', 'Saint Pierre and Miquelon'),
    ('ESH', '서사하라', 'Western Sahara'),
    ('SEN', '세네갈', 'Senegal'),
    ('SRB', '세르비아', 'Serbia'),
    ('SYC', '세이셸', 'Seychelles'),
    ('LCA', '세인트루시아', 'Saint Lucia'),
    ('VCT', '세인트빈센트그레나딘', 'Saint Vincent and the Grenadines'),
    ('KNA', '세인트키츠 네비스', 'Saint Kitts and Nevis'),
    ('SHN', '세인트헬레나', 'Saint Helena, Ascension and Tristan da Cunha'),
    ('SOM', '소말리아', 'Somalia'),
    ('SLB', '솔로몬 제도', 'Solomon Islands'),
    ('SDN', '수단', 'Sudan'),
    ('SUR', '수리남', 'Suriname'),
    ('LKA', '스리랑카', 'Sri Lanka'),
    ('SJM', '스발바르제도-얀마웬섬', 'Svalbard and Jan Mayen'),
    ('SWE', '스웨덴', 'Sweden'),
    ('CHE', '스위스', 'Switzerland'),
    ('ESP', '스페인', 'Spain'),
    ('SVK', '슬로바키아', 'Slovakia'),
    ('SVN', '슬로베니아', 'Slovenia'),
    ('SYR', '시리아', 'Syria'),
    ('SLE', '시에라리온', 'Sierra Leone'),
    ('SXM', '신트마르턴', 'Sint Maarten (Dutch part)'),
    ('SGP', '싱가포르', 'Singapore'),
    ('ARE', '아랍에미리트', 'United Arab Emirates'),
    ('ABW', '아루바', 'Aruba'),
    ('ARM', '아르메니아', 'Armenia'),
    ('ARG', '아르헨티나', 'Argentina'),
    ('ASM', '아메리칸 사모아', 'American Samoa'),
    ('ISL', '아이슬란드', 'Iceland'),
    ('HTI', '아이티', 'Haiti'),
    ('IRL', '아일랜드', 'Ireland'),
    ('AZE', '아제르바이잔', 'Azerbaijan'),
    ('AFG', '아프가니스탄', 'Afghanistan'),
    ('AND', '안도라', 'Andorra'),
    ('ALB', '알바니아', 'Albania'),
    ('DZA', '알제리', 'Algeria'),
    ('AGO', '앙골라', 'Angola'),
    ('ATG', '앤티가 바부다', 'Antigua and Barbuda'),
    ('AIA', '앵귈라', 'Anguilla'),
    ('ERI', '에리트리아', 'Eritrea'),
    ('SWZ', '에스와티니', 'Eswatini'),
    ('EST', '에스토니아', 'Estonia'),
    ('ECU', '에콰도르', 'Ecuador'),
    ('ETH', '에티오피아', 'Ethiopia'),
    ('SLV', '엘살바도르', 'El Salvador'),
    ('GBR', '영국', 'United Kingdom'),
    ('VGB', '영국령 버진아일랜드', 'Virgin Islands, British'),
    ('YEM', '예멘', 'Yemen'),
    ('OMN', '오만', 'Oman'),
    ('AUS', '오스트레일리아', 'Australia'),
    ('AUT', '오스트리아', 'Austria'),
    ('HND', '온두라스', 'Honduras'),
    ('ALA', '올란드 제도', 'Åland Islands'),
    ('JOR', '요르단', 'Jordan'),
    ('UGA', '우간다', 'Uganda'),
    ('URY', '우루과이', 'Uruguay'),
    ('UZB', '우즈베키스탄', 'Uzbekistan'),
    ('UKR', '우크라이나', 'Ukraine'),
    ('IRQ', '이라크', 'Iraq'),
    ('IRN', '이란', 'Iran'),
    ('ISR', '이스라엘', 'Israel'),
    ('EGY', '이집트', 'Egypt'),
    ('ITA', '이탈리아', 'Italy'),
    ('IND', '인도', 'India'),
    ('IDN', '인도네시아', 'Indonesia'),
    ('JPN', '일본', 'Japan'),
    ('JAM', '자메이카', 'Jamaica'),
    ('ZMB', '잠비아', 'Zambia'),
    ('JEY', '저지', 'Jersey'),
    ('GNQ', '적도 기니', 'Equatorial Guinea'),
    ('GEO', '조지아', 'Georgia'),
    ('CHN', '중국', 'China'),
    ('CAF', '중앙 아프리카 공화국', 'Central African Republic'),
    ('DJI', '지부티', 'Djibouti'),
    ('GIB', '지브롤터', 'Gibraltar'),
    ('ZWE', '짐바브웨', 'Zimbabwe'),
    ('TCD', '차드', 'Chad'),
    ('CZE', '체코', 'Czechia'),
    ('CHL', '칠레', 'Chile'),
    ('CMR', '카메룬', 'Cameroon'),
    ('CPV', '카보베르데', 'Cabo Verde'),
    ('KAZ', '카자흐스탄', 'Kazakhstan'),
    ('QAT', '카타르', 'Qatar'),
    ('KHM', '캄보디아', 'Cambodia'),
    ('CAN', '캐나다', 'Canada'),
    ('KEN', '케냐', 'Kenya'),
    ('CYM', '케이맨 제도', 'Cayman Islands'),
    ('COM', '코모로', 'Comoros'),
    ('CRI', '코스타리카', 'Costa Rica'),
    ('CCK', '코코스 제도', 'Cocos (Keeling) Islands'),
    ('CIV', '코트디부아르', "Côte d'Ivoire"),
    ('COL', '콜롬비아', 'Colombia'),
    ('COG', '콩고공화국', 'Congo'),
    ('COD', '콩고민주공화국', 'Congo, The Democratic Republic of the'),
    ('CUB', '쿠바', 'Cuba'),
    ('KWT', '쿠웨이트', 'Kuwait'),
    ('COK', '쿡 제도', 'Cook Islands'),
    ('CUW', '퀴라소', 'Curaçao'),
    ('HRV', '크로아티아', 'Croatia'),
    ('CXR', '크리스마스섬', 'Christmas Island'),
    ('KGZ', '키르기스스탄', 'Kyrgyzstan'),
    ('KIR', '키리바시', 'Kiribati'),
    ('CYP', '키프로스', 'Cyprus'),
    ('TJK', '타지키스탄', 'Tajikistan'),
    ('TZA', '탄자니아', 'Tanzania'),
    ('THA', '태국', 'Thailand'),
    ('TCA', '터크스 케이커스 제도', 'Turks and Caicos Islands'),
    ('TGO', '토고', 'Togo'),
    ('TKL', '토켈라우', 'Tokelau'),
    ('TON', '통가', 'Tonga'),
    ('TKM', '투르크메니스탄', 'Turkmenistan'),
    ('TUV', '투발루', 'Tuvalu'),
    ('TUN', '튀니지', 'Tunisia'),
    ('TUR', '튀르키예', 'Türkiye'),
    ('TTO', '트리니다드 토바고', 'Trinidad and Tobago'),
    ('PAN', '파나마', 'Panama'),
    ('PRY', '파라과이', 'Paraguay'),
    ('PAK', '파키스탄', 'Pakistan'),
    ('PNG', '파푸아뉴기니', 'Papua New Guinea'),
    ('PLW', '팔라우', 'Palau'),
    ('PSE', '팔레스타인', 'Palestine, State of'),
    ('FRO', '페로 제도', 'Faroe Islands'),
    ('PER', '페루', 'Peru'),
    ('PRT', '포르투갈', 'Portugal'),
    ('FLK', '포클랜드 제도', 'Falkland Islands (Malvinas)'),
    ('POL', '폴란드', 'Poland'),
    ('PRI', '푸에르토리코', 'Puerto Rico'),
    ('FRA', '프랑스', 'France'),
    ('GUF', '프랑스령 기아나', 'French Guiana'),
    ('PYF', '프랑스령 폴리네시아', 'French Polynesia'),
    ('FJI', '피지', 'Fiji'),
    ('FIN', '핀란드', 'Finland'),
    ('PHL', '필리핀', 'Philippines'),
    ('PCN', '핏케언 제도', 'Pitcairn'),
    ('HUN', '헝가리', 'Hungary'),
    ('HKG', '홍콩', 'Hong Kong'),
]

COUNTRY_NAMES = {iso3: ko for iso3, ko, _ in COUNTRIES}
COUNTRY_NAMES_EN = {iso3: en for iso3, _, en in COUNTRIES}
